segmentation:
  config_path: "CIDAS/clipseg-rd64-refined"
  call_openvino: False

depth_estimation:
  model_path: "depth_estimation/Depth_Anything_V2/checkpoints/depth_anything_v2_vits.pth"
  config_path: "vits"
  optimize_for: "speed"
  call_openvino: False

pose_estimation:
  model_path: "models/yolo/yolo11m-pose.pt"
  threshold: 0.7
  use_gpu: true
  call_openvino: False

action_recognizer:
  threshold_distance: 50
  use_depth: False

dataset:
  action_dataset: "dataset/"
  frames_path: 'dataset/frames'
  videos_path: 'dataset/videos'
  masks_path: 'dataset/action_dataset/masks'
  keypoints_path: 'dataset/action_dataset/keypoints'

  labels_path: "dataset/action_dataset/labels.csv"


settings:
  device: "cpu"
  log_dir: "logs/"
  rtsp: "data/frames/frames_laptop1"
  frames_output_dir: "data/annotated_frames/annotated_frames_laptop1"