segmentation:
  config_path: "CIDAS/clipseg-rd64-refined"
  call_openvino: False

depth_estimation:
  model_path: "depth_estimation/Depth-Anything-V2/checkpoints/depth_anything_v2_vits.pth"
  config_path: "vits"
  optimize_for: "speed"
  call_openvino: False

pose_estimation:
  model_path: "pose_estimation/yolo/yolo11m-pose.pt"
  threshold: 0.7
  use_gpu: true
  call_openvino: False

action_recognizer:
  threshold_distance: 50

dataset:
  frames_path: "/Users/anastasiaspileva/Desktop/actions/frames"
  videos_path: "/Users/anastasiaspileva/Desktop/actions/videos"

  train_labels_path: "/Users/anastasiaspileva/Desktop/actions/train.csv"
  valid_labels_path: "/Users/anastasiaspileva/Desktop/actions/valid.csv"

  action_dataset: "/Users/anastasiaspileva/Desktop/actions"
  all_labels_path: "/Users/anastasiaspileva/Desktop/actions/labels.npy"


settings:
  device: "cpu"
  log_dir: "logs/"
  rtsp: "data/frames/frames_laptop1"
  frames_output_dir: "data/annotated_frames/annotated_frames_laptop1"